# Default values for front-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  name: 'react-app'
  namespace: 'frontend'


replicas:
  count: 1
  revisionHistoryLimit: 0

image:
  version: main-7488d01
  repository: 142373294051.dkr.ecr.us-east-1.amazonaws.com/frontend
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

