name: Push Docker image to ECR and update to Github

on:
  release:
    types: [published]
  push:
    branches: [ "main" ]

jobs:
  push_to_registry_frontend:  
    name: Push Frontend Docker image to ECR
    runs-on: ubuntu-18.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set Outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Configure AWS creddentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          
      - name: Build and push
        uses: docker/build-push-action@v2 # build-push-action 사용
        with:
          context: ./Frontend
          push: true
          tags: |
            ${{ secrets.REGISTRY }}/react-app:${{ steps.extract_branch.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
            ${{ secrets.REGISTRY }}/react-app:latest
          cache-from: type=gha # 여기서 gha 는 Guthub Actions 용 캐시를 의미합니다.
          cache-to: type=gha,mode=max

  deploy:  
    name: Edit deploy.yaml and deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Update Version react-app
        run: |
            git_hash=$(git rev-parse --short "$GITHUB_SHA")
            version=$(cat ./Frontend/front-app/values.yaml | grep version: | awk '{print $2}')
            sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./Frontend/front-app/values.yaml

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
          commit_message: Version updated
            
